#!/usr/bin/env python3
"""Builds census_homes.js (Zip/FSA -> occupied housing count, official census).

Sources (both free):
  US  : Census ACS 2023 5-yr, B25002_002E occupied housing units per ZCTA
        (needs US_CENSUS_API_KEY in .env -- free key: https://api.census.gov/data/key_signup.html)
  Canada : StatCan 2021 Census Profile, CHARACTERISTIC_ID=5 "Private dwellings
        occupied by usual residents" per FSA, from the bulk CSV:
        https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/download-telecharger.cfm
        (Forward sortation areas -> CSV), unzip 98-401-X2021013_English_CSV_data.csv into data/

Run: python3 build_census_homes.py   (after the above download)
"""

import csv, json, os, urllib.request

# --- key from .env (never printed, never committed) -----------------------
key = os.environ.get("US_CENSUS_API_KEY")
if not key and os.path.exists(".env"):
    for line in open(".env"):
        if line.startswith("US_CENSUS_API_KEY="):
            key = line.split("=", 1)[1].strip().strip('"').strip("'")
if not key:
    raise SystemExit("US_CENSUS_API_KEY not set (.env or environment)")

out = {}

# --- US: one API call, all ZCTAs ------------------------------------------
url = (
    "https://api.census.gov/data/2023/acs/acs5?get=B25002_002E,B25001_001E"
    f"&for=zip%20code%20tabulation%20area:*&key={key}"
)
with urllib.request.urlopen(url, timeout=120) as r:
    rows = json.load(r)
us = 0
for occ, total, zcta in rows[1:]:
    n = (
        int(occ)
        if occ not in (None, "", "-")
        else (int(total) if total not in (None, "", "-") else None)
    )
    if n is not None:
        out[zcta] = n
        us += 1
print(f"US: {us} zips")

# --- Canada: stream the 645MB profile CSV, keep char id 5 (fall back 4) ----
ca, fsa_vals = 0, {}
with open(
    "data/98-401-X2021013_English_CSV_data.csv", newline="", encoding="latin-1"
) as f:
    for row in csv.reader(f):
        if row[3] != "Forward sortation area":
            continue
        fsa, cid, val = row[2], row[8], row[11]
        if val.isdigit() and cid in ("4", "5"):
            fsa_vals.setdefault(fsa, {})[cid] = val
for fsa, vals in fsa_vals.items():
    out[fsa] = int(vals.get("5") or vals.get("4"))
    ca += 1
print(f"CA: {ca} FSAs")

with open("census_homes.js", "w", encoding="utf-8") as f:
    f.write(
        "// Zip/FSA -> occupied housing count (US: Census ACS 2023 5yr B25002; CA: StatCan 2021 Profile char 5).\n"
    )
    f.write("// Generated by build_census_homes.py.\n")
    f.write("const CENSUS_HOMES = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")
print(f"wrote census_homes.js with {len(out)} codes")
