#!/usr/bin/env python3
"""Builds census_homes.js (Zip/FSA -> lawncare-eligible occupied dwellings).

"Eligible" = occupied dwellings that are houses rather than apartments:
detached, semi/row/townhouse (US 1-attached), duplex/2-unit, other
single-attached, and mobile/movable. Apartment and condo units are excluded.

Sources (both free):
  US  : Census ACS 2023 5-yr, B25032 (tenure x units in structure) per ZCTA,
        owner+renter for eligible structure rows
        (needs US_CENSUS_API_KEY in .env -- free key: https://api.census.gov/data/key_signup.html)
  Canada : StatCan 2021 Census Profile, occupied private dwellings by
        structural type per FSA from the bulk CSV (characteristic ids
        42,43,44,45,48,49 = detached/semi/row/duplex/other-attached/movable):
        https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/download-telecharger.cfm
        (Forward sortation areas -> CSV), unzip 98-401-X2021013_English_CSV_data.csv into data/

Run: python3 build_census_homes.py   (after the above download)
"""

import csv, json, os, urllib.request

# --- key from .env (never printed, never committed) -----------------------
key = os.environ.get("US_CENSUS_API_KEY")
if not key and os.path.exists(".env"):
    for line in open(".env"):
        if line.startswith("US_CENSUS_API_KEY="):
            key = line.split("=", 1)[1].strip().strip('"').strip("'")
if not key:
    raise SystemExit("US_CENSUS_API_KEY not set (.env or environment)")

out = {}

# --- US: one API call, all ZCTAs ------------------------------------------
# B25032 owner(002-012)/renter(013-023) by structure; eligible rows:
# 1-detached, 1-attached, 2-unit, mobile (owner: 003,004,005,011; renter: 014,015,016,022)
ELIG = [
    "B25032_003E",
    "B25032_004E",
    "B25032_005E",
    "B25032_011E",
    "B25032_014E",
    "B25032_015E",
    "B25032_016E",
    "B25032_022E",
]
url = (
    "https://api.census.gov/data/2023/acs/acs5?get=B25002_002E,"
    + ",".join(ELIG)
    + f"&for=zip%20code%20tabulation%20area:*&key={key}"
)
with urllib.request.urlopen(url, timeout=120) as r:
    rows = json.load(r)
hdr = rows[0]
i_elig = [hdr.index(v) for v in ELIG]
i_occ = hdr.index("B25002_002E")
us = skipped = impossible = 0
for rec in rows[1:]:
    zcta, vals = rec[-1], rec[:-1]
    try:
        occ = int(vals[i_occ])
        elig = sum(int(vals[i]) for i in i_elig)
    except ValueError:  # API suppression marker (e.g. -666666666)
        skipped += 1
        continue
    if elig > occ:
        impossible += (
            1  # sanity: eligible structure rows must not exceed occupied total
        )
        continue
    out[zcta] = elig
    us += 1
print(f"US: {us} zips ({skipped} suppressed, {impossible} sanity-skipped)")

# --- Canada: stream the 645MB profile CSV, sum eligible structure ids -----
# 42 single-detached, 43 semi, 44 row, 45 duplex, 48 other single-attached,
# 49 movable. (46/47 = apartments, excluded.)
CA_ELIG = {"42", "43", "44", "45", "48", "49"}
ca, fsa_vals = 0, {}
with open(
    "data/98-401-X2021013_English_CSV_data.csv", newline="", encoding="latin-1"
) as f:
    for row in csv.reader(f):
        if row[3] != "Forward sortation area":
            continue
        fsa, cid, val = row[2], row[8], row[11]
        if val.isdigit() and cid in CA_ELIG:
            fsa_vals[fsa] = fsa_vals.get(fsa, 0) + int(val)
for fsa, total in fsa_vals.items():
    out[fsa] = total
    ca += 1
print(f"CA: {ca} FSAs")

with open("census_homes.js", "w", encoding="utf-8") as f:
    f.write(
        "// Zip/FSA -> lawncare-eligible occupied dwellings (US: ACS 2023 5yr B25032 owner+renter\n"
        "// detached/1-attached/2-unit/mobile; CA: StatCan 2021 Profile char 42-45,48,49; apartments excluded).\n"
    )
    f.write("// Generated by build_census_homes.py.\n")
    f.write("const CENSUS_HOMES = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")
print(f"wrote census_homes.js with {len(out)} codes")
