#!/usr/bin/env python3
"""Builds centroids.js from GeoNames postal code dumps (data/US.txt, data/CA.txt).
Source data: https://download.geonames.org/export/zip/  (CC BY 4.0)
Re-run after refreshing the dumps:  python3 build_centroids.py
"""

import json

out = {}
for country in ("US", "CA"):
    with open(f"data/{country}.txt", encoding="utf-8") as f:
        for line in f:
            cols = line.split("\t")
            code, lat, lng = cols[1], cols[9], cols[10]
            out[code] = [round(float(lat), 4), round(float(lng), 4)]

with open("centroids.js", "w", encoding="utf-8") as f:
    f.write("// Zip (US, 5-digit) and FSA (Canada) -> [lat, lng] centroids.\n")
    f.write(
        "// Generated by build_centroids.py from GeoNames postal data (CC BY 4.0, geonames.org)\n"
    )
    f.write("const CENTROIDS = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")

print(f"wrote centroids.js with {len(out)} codes")
