#!/usr/bin/env python3
"""Builds boundaries.js (Zip/FSA -> polygons) from simplified GeoJSON intermediates.

Pipeline (run from repo root):
  1. Download sources (one-time):
     curl -o data/zcta.zip https://www2.census.gov/geo/tiger/GENZ2020/shp/cb_2020_us_zcta520_500k.zip
     curl -A "Mozilla/5.0" -o data/fsa.zip "https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/files-fichiers/lfsa000b21a_e.zip"
     unzip into data/zcta/ and data/fsa/
  2. Simplify + reproject:
     npx mapshaper data/zcta/cb_2020_us_zcta520_500k.shp -simplify 1.2% keep-shapes -o format=geojson precision=0.0001 /tmp/opencode/zcta.json
     npx mapshaper data/fsa/lfsa000b21a_e/lfsa000b21a_e.shp -proj wgs84 -simplify 1.2% keep-shapes -o format=geojson precision=0.0001 /tmp/opencode/fsa.json
  3. python3 build_boundaries.py

Sources: US Census Bureau ZCTA 2020 (public domain),
         Statistics Canada FSA 2021 (Open Government Licence - Canada).
"""

import json


def rings_latlng(geom):
    """Polygons as [outer, hole1, ...] ring lists in [lat,lng] (Leaflet order).

    Holes matter: StatCan L4H wraps around Kleinburg (L0J) -- dropping the
    hole made L4H's fill overlap L0J on the map. Leaflet draws holes when a
    polygon is passed as [outer, holes...].
    """
    gtype, coords = geom["type"], geom["coordinates"]
    polys = coords if gtype == "MultiPolygon" else [coords]
    out = []
    for poly in polys:
        rings = [
            [[round(lat, 4), round(lng, 4)] for lng, lat in ring]
            for ring in poly
            if len(ring) >= 3
        ]
        if rings:
            out.append(rings)
    return out


out = {}
for src, key in (
    ("/tmp/opencode/zcta.json", "ZCTA5CE20"),
    ("/tmp/opencode/fsa.json", "CFSAUID"),
):
    with open(src, encoding="utf-8") as f:
        data = json.load(f)
    n = 0
    for feat in data["features"]:
        code = feat["properties"].get(key)
        if code and feat.get("geometry"):
            out[code] = rings_latlng(feat["geometry"])
            n += 1
    print(f"{src}: {n} features")

with open("boundaries.js", "w", encoding="utf-8") as f:
    f.write(
        "// Zip/FSA -> array of polygons; polygon = [outer ring, hole rings...] ([lat,lng]).\n"
    )
    f.write(
        "// Generated by build_boundaries.py. US: Census ZCTA 2020 (public domain);\n"
    )
    f.write("// CA: StatCan FSA 2021 (OGL-Canada). Simplified ~1.2%.\n")
    f.write("const BOUNDARIES = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")

import os

print(
    f"wrote boundaries.js with {len(out)} codes, {os.path.getsize('boundaries.js') / 1e6:.1f} MB"
)
